### PR TITLE
Fix memory leak allocated with 'gtk_builder_new ()'

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
There is a conflict with master branch.

**Comment by rbuj** [comment]
@raveit65 done

**Comment by raveit65** [comment]
@rbuj 
It looks ok, but why is it needed to renaming a variable name?
Wouldn't  `g_object_unref (ui);` work too?

**Comment by rbuj** [comment]
@raveit65 
I changed the variable name to keep consistency with other source files, in addition `ui` is used mainly with GtkUIManager.

**Pull request merged**
