### PR TITLE
xattr-tags-extension: avoid check xattr for mtp://

### PR DESCRIPTION
**Pull request by kreijack**
Some protocols (like mtp://), doesn't support xattr. In this case avoid to check the xattr-tags to not have
poor performance.

This patch blacklists mtp:// and gphoto2://.

The problem that I try to solve is that when I browser the camera files of my phone, it took up to 3.5 minutes to show ~500 files when xattr-tags is enabled; without this extension it requires 20 seconds (still a lot, but it is comparable to what Window does).

Blacklisting the mtp:// protocol, it requires 20 seconds again even with the xattr-tags extension enabled.

However I am not sure about two points:
- now the blacklist is a static list; I was unable to find in a programmatically way which protocol supports xattr
- I saw that caja don't try to update the xattr of file using the MTP protocol; so in any case it seems that caja is already aware of which protocol is capable to update xattr. It would be useful to share this kind of information even with xattr-tags.

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
I don't have anything I normally connect via gphoto, but this SERIOUSLY improves performance in reading directories in Android devices over mtp.

**Comment by lukefromdc** [comment]
app.travis-ci.com seems to be unreachable at the moment,so no info available on the Debian build failure, might be a problem on that end. PR built fine here, on Debian Unstable

**Comment by raveit65** [comment]
`.build.yml` needs to be update for debian.
https://app.travis-ci.com/github/mate-desktop/caja-extensions/jobs/587661117#L227
```
E: Unable to locate package libgupnp-1.2-dev
E: Couldn't find any package by glob 'libgupnp-1.2-dev'
```
https://github.com/mate-desktop/caja-extensions/blob/master/.build.yml#L37

Seems debian:testing is using `libgupnp-1.6-dev` now.
https://packages.debian.org/testing/libgupnp-1.6-dev

**Comment by raveit65** [comment]
Updating deps helps. https://github.com/mate-desktop/caja-extensions/commit/3b76b25088a2b94de74178d2afa13c7a921b4820
https://app.travis-ci.com/github/mate-desktop/caja-extensions/builds/257507945

**Comment by raveit65** [comment]
@kreijack 
Build fix for debian is in master branch.
https://github.com/mate-desktop/caja-extensions/commit/d36c7233d22f23dd42683f1b67764dc2782ddc40
Can you please rebase your branch with our master?

**Comment by kreijack** [comment]
> I don't have anything I normally connect via gphoto, but this SERIOUSLY improves performance in reading directories in Android devices over mtp.

My canon camera (sx 270hs) is seen via gphoto2://.

However, it would be useful to know if any other protocol has the same problem... even tough I incline to think that xdg.tags are valid only on local fielsystem (file://, admin://); I saw  that gnomevfs doesn't support xattr over nfs:// either...

May be that the black list should be changed in a "white list" allowing only file:// and admin:// ?

**Comment by raveit65** [comment]
@kreijack 
Sorry for late response.
I use nfs to share directories for VMs on my box. In a test with a large picture dir (3.712 Objects, 6,9 GiB) i could not see a difference with xattr enabled or disabled.
It seems that xattr is supported by nfs with kernel-5.9. https://www.phoronix.com/news/Linux-5.9-NFS-Server-User-Xattr
With mtp using my android device i noticed a speed up when xattr is disabled.
So i think current state of PR is good.
Can you rename commit body please?
Commit isn't mtp only.

**Comment by raveit65** [comment]
Mixed usage of tabs and spaces in your commit. Please do not use tabs.
Whole the file use spaces....

**Comment by kreijack** [comment]
@raveit65 , as per your request I updated commit first row and removed the tab.

**Review by raveit65 — APPROVED** [review]
LGTM

**Pull request merged**
