### PR TITLE
Fix missing GtkRadioButton id

### PR DESCRIPTION
**Pull request by dahenry**
Add missing id to custom scale radio button referenced in caja-image-resizer.c This fixes issue #104.

### CODE REVIEW

**Review by lukefromdc — APPROVED** [review]
This works, resizing an image now follows a selected scale option and did not before

**Comment by raveit65** [comment]
Hmm, pulling the repo failed for some reasons.
```
[rave@mother caja]$ git checkout -b dahenry-patch-1 master
Switched to a new branch 'dahenry-patch-1'
[rave@mother caja]$ curl -L https://github.com/mate-desktop/caja-extensions/pull/117.patch | git am -3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1198    0  1198    0     0   1355      0 --:--:-- --:--:-- --:--:--  3017
Applying: Fix missing GtkRadioButton id
error: sha1 information is lacking or useless (image-converter/caja-image-resize.ui).
error: could not build fake ancestor
Patch failed at 0001 Fix missing GtkRadioButton id
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```
Looks like broken hash sum. I never saw that in git before.

**Comment by raveit65** [comment]
The repo is deleted https://github.com/dahenry?tab=repositories

**Review by raveit65 — APPROVED** [review]
LGTM,
this fixes the issue

**Pull request merged**
