### PR TITLE
caja-image-resizer: fix memory leak pointed to by 'size'

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by raveit65** [comment]
@rbuj 
Where do you see the warning about this leak?

**Comment by raveit65** [comment]
@rbuj
Where do you see the warning about this leak?

**Comment by rbuj** [comment]
I remember that it was detected by using a run-time memory leak detector, but I don't remember which sanitizer I used. If you think it is necessary then I will try to detect it again but keep in mind that dependencies must be compiled too.

```shell
#!/bin/bash
BASERAMDIR=/home/robert/sanitizer
REPORTDIR=$BASERAMDIR

mkdir -p $BASERAMDIR

while read i
do
  echo $i
  cd $BASERAMDIR
  rm -fr $BASERAMDIR/$i
  echo -ne ' + Clone: '; git clone --quiet "https://github.com/mate-desktop/"$i".git" &> /dev/null && echo OK || echo Failed
  cd $BASERAMDIR/$i

  CFLAGS="-ggdb3 -O0 -fsanitize=address"
  CONF="--prefix=/usr"
  case "$i" in
    libmatekbd|libmateweather|mate-applets|mate-media|mate-menus|mate-notification-daemon|pluma) # missing MATE_DEBUG_CHECK
      CONF+=" --enable-compile-warnings=maximum"
      ;;
    engrampa|marco|mate-control-center|mate-desktop|mate-panel|mate-power-manager|mate-polkit|mate-session-manager|mate-screensaver|mate-system-monitor|mate-terminal|mate-utils) # MATE_DEBUG_CHECK + MATE_COMPILER_WARNINGS
      CONF+=" --disable-debug --enable-compile-warnings=maximum"
      ;;
    eom) # enable eom-thumbnailer + MATE_DEBUG_CHECK + MATE_COMPILER_WARNINGS
      CONF+=" --disable-debug --enable-compile-warnings=maximum --enable-thumbnailer --without-gdk-pixbuf-thumbnailer"
      ;;
    atril) # missing MATE_DEBUG_CHECK
      CONF+=" --disable-debug --enable-compile-warnings=maximum"
      ;;
    caja|caja-extensions|mate-indicator-applet|mate-sensors-applet|mate-settings-daemon|mate-user-share|mozo|python-caja) # missing MATE_DEBUG_CHECK, MATE_COMPILER_WARNINGS
      ;;
  esac
  echo -ne ' + Configure, Make, Install: '; CFLAGS="${CFLAGS}" ./autogen.sh ${CONF} &> $REPORTDIR/$i.conf.log && make &> $REPORTDIR/$i.make.log && sudo make install &> /dev/null
  if [ $? -eq 0 ]; then
    echo OK
  else
    echo Failed
  fi
done <<< "mate-common
mate-desktop
mate-settings-daemon
atril
caja
caja-extensions
engrampa
eom
libmatekbd
libmatemixer
libmateweather
marco
mate-backgrounds
mate-applets
mate-calc
mate-control-center
mate-icon-theme
mate-media
mate-menus
mate-panel
mate-polkit
mate-power-manager
mate-screensaver
mate-sensors-applet
mate-session-manager
mate-system-monitor
mate-terminal
mate-themes
mate-user-guide
mate-utils
mozo
pluma"
```

**Comment by raveit65** [comment]
NP, only a little hint in PR would be nice.
Than people know that they have to compile the application with 
`CFLAGS="-g -O0 -fsanitize=address" ./autogen.sh --prefix=/usr/local && make V=1 && sudo make install`
first, when `libasan libasan-static` is installed
To avoid unnecessary reading of build logs ;)

PS: maybe you like to write a short wiki entry how to use sanitiser from libsan?

**Pull request merged**
