### PR TITLE
sendto: remove gajim plugin

### PR DESCRIPTION
**Pull request by yetist**
Gajim no longer provides dbus interfaces such as list_accounts, prefs_list, list_contacts, send_file, etc.
So, we cannot send files for gajim contacts.

### CODE REVIEW

**Comment by raveit65** [comment]
`make distcheck` runs fine. Is there a changelog entry in gajim about stopping the dbus support, or git commit, etc ?

**Review by raveit65 — APPROVED** [review]
LGTM

**Review by zhuyaliang — APPROVED** [review]
Remove unused files and APIs to reduce our workload

**Comment by yetist** [comment]
Sorry, it looks like the dbus interface for gajim still exists.

**Pull request closed without merging**
