### PR TITLE
Added xattr-tags-property-page plugin.

### PR DESCRIPTION
**Pull request by fbarriga**
With this plugin the user can add/remove/edit tags from files. The tags are stored using `xattrs`.

More details can be found here: https://github.com/mate-desktop/caja-extensions/issues/27

Preview:
47e106a0-1177-11e7-9ba2-ff7d0b6eac08

### CODE REVIEW

**Comment by raveit65** [comment]
Can we remove those build warnings please?
```
caja-xattr-tags-property-page-extension.c:629:1: warning: 'caja_xattr_tags_properties_page_provider_class_init' defined but not used [-Wunused-function]
 caja_xattr_tags_properties_page_provider_class_init (
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
caja-xattr-tags-property-page-extension.c:622:1: warning: 'caja_xattr_tags_properties_page_provider_init' defined but not used [-Wunused-function]
 caja_xattr_tags_properties_page_provider_init (
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
caja-xattr-tags-property-page-extension.c:607:1: warning: 'property_page_provider_iface_init' defined but not used [-Wunused-function]
 property_page_provider_iface_init (CajaPropertyPageProviderIface *iface)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Not a show-stopper or is this for following implementations?

**Comment by raveit65** [comment]
A cosmetic suggestion. Can you use a shadow-type for the scrolledwindow, please?
https://github.com/mate-desktop/caja-extensions/pull/33/commits/dc78c0e368c1c75b096177b53703d5630a5f38c8#diff-1f1c94a91ea4f47760991e0c67e5df81R242
```
gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolled_window),
                                     GTK_SHADOW_IN);
```
This will add the .frame style class to the scrolledwindow. In css language
scrolledwindow --> scrolledwindow.frame
Reason is that most gtk themes set a border to **scrolledwindow.frame** but not to **scrolledwindow**.
Before:
xattr-tags-property-sw-page-without-border
After:
xattr-tags-property-sw-page-with-border
xattr-tags-property-sw-page-with-border-2
This is with BlueMenta theme, but gtk+ adwaita theme makes the same different.

The rest looks good to me and someone can do a code review.
....nice work.

**Comment by fbarriga** [comment]
@monsta I think that an extension is better than a separate app. KDE's dolphin has tag support and Apple's macOS finder also include it.
Currently on caja you can:
- add notes to files
- change permissions
- share
- compress
- set as wallpaper / rotate / resize images

So having the ability to tag files is pretty natural (and we already support searching tags and displaying them on a column).

**Comment by fbarriga** [comment]
@raveit65 I updated the PR:
- set the shadow type for the scrolled window
- remove dead code (unused functions)

**Comment by raveit65** [comment]
Historical all extensions were packed in a single package for every extensions.
And in gnome-2 days every package did have his own maintainer.
With MATE-1.8 we moved all extension to one package to reduce the workload to maintain it here and for downstream distro maintainers.
For me it is is a extension, as it is a very small tool and limited to caja, and the right place is caja-extension or a single extension package.
But sadly, i have to agree with @monsta , as i am not able to maintain this new code for my own.
And we are a small team with a heavy workload, so in the end it's a decision by @monsta, as he is the only one who can maintain it.
.... we really need someone who want to help us to maintain caja-extensions....

**Comment by fbarriga** [comment]
@raveit65 I can maintain the 2 extensions that I've created (`xattr_tags_property_page_final` and ` xattr-tags`)

**Comment by raveit65** [comment]
@fbarriga 
Cool, i am fine with that :-)
It's not bad to visit us as irc freenode channel mate-dev.
@monsta @flexiondotorg 
Do you agree?

**Comment by flexiondotorg** [comment]
I agree 😀

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by monsta** [comment]
> For me it is is a extension, as it is a very small tool and limited to caja, and the right place is caja-extension or a single extension package.

Well, it's an editor for a kind of data that can be used in other file managers as well.
I think about [eiciel](http://rofi.roger-ferrer.org/eiciel/). It's a standalone app editor + Nautilus extension built from the same code. There's a patch for it to make Caja extension at https://github.com/mate-desktop/caja/issues/511. Same could be done for Nemo for example.

**Comment by raveit65** [comment]
@monsta 
>> For me it is is a extension, as it is a very small tool and limited to caja, and the right place is caja-extension or a single extension package.

> Well, it's an editor for a kind of data that can be used in other file managers as well.
I think about [eiciel](http://rofi.roger-ferrer.org/eiciel/). It's a standalone editor + Nautilus extension built from the same code. There's a patch for it to make Caja extension at https://github.com/mate-desktop/caja/issues/511. Same could be done for Nemo for example.

Sadly this solution is untested.
*more* sadly, this package is maintained by audacious maintainer in fedora :-)
https://admin.fedoraproject.org/pkgdb/package/rpms/eiciel/
At this point i am out and using eiciel is a *no go* for me.
Feel free to find another fedora maintainer for your prefered solution.
For the meanwhile we should add this code and support @fbarriga to mainain his caja-extensions.
I know you're afraid that code becomes the same state than libmatemixer or epub support in atril.
But i prefer to invite new ppl if they want support us, as thinking about ppl which have left us ;-)
My 3.14...... cents

@fbarriga 
would be nice to see you at irc freenode channel #mate-dev, as this is our prefered communication channel.

**Comment by raveit65** [comment]
Hmm, nobody answering here any more.
@fbarriga 
What do you think about to create a single caja extension at github?
I am happy to include it in fedora.
Another solution is to use it as patch for fedora if you maintain your caja-extension fork at github.

Seriously, i won't add the other application in fedora.

**Comment by darkshram** [comment]
In case you are interested, I have forked eiciel (along with support for acl & xattr for Caja).
https://github.com/darkshram/mate-eiciel/

**Comment by darkshram** [comment]
If somebody is interested, I have written a patch for Tracker 1.12.3 to support Caja. In other words, this adds support to Caja for Tracker tags.

virtualbox_aldos-test_22_09_2017_05_03_45

[tracker-1.12.3-caja-support.zip](https://github.com/mate-desktop/caja-extensions/files/1324116/tracker-1.12.3-caja-support.zip)

**Comment by fbarriga** [comment]
@raveit65 I just created a repo that only has this extension: 
https://github.com/fbarriga/caja-xattrs

I guess that the repo could be moved into `mate-desktop` github project.
The version is 0.1.0, I don't know if it should be synced with mate version.

**Comment by raveit65** [comment]
@monsta @flexiondotorg 
Do you agree to add the extension as single application with @fbarriga as maintainer?

**Comment by raveit65** [comment]
Yes, i would like to see a useful new application inside Mate with a new developer.
And i like to add it to fedora.

**Comment by flexiondotorg** [comment]
I agree that bringing `caja-xattrs`, and the maintainer, into the MATE project would be a positive move. 

@fbarriga How would you like to proceed? I can import https://github.com/fbarriga/caja-xattrs to this mate-desktop organisation, add you to the team with direct commit access to caja-xattrs. How does that sound?

Is this the same/similar caja-xattrs extension that we have in caja-extensions? If so, I assume we will be dropping caja-xattrs from caja-extensions?

**Comment by fbarriga** [comment]
@flexiondotorg 
> @fbarriga How would you like to proceed? I can import https://github.com/fbarriga/caja-xattrs to this mate-desktop organisation, add you to the team with direct commit access to caja-xattrs. How does that sound?

sounds great :)

> Is this the same/similar caja-xattrs extension that we have in caja-extensions? If so, I assume we will be dropping caja-xattrs from caja-extensions?

Nope, the one on `caja-extensions` add the tag support on columns. This add a new tab on the properties page.

**Comment by flexiondotorg** [comment]
Welcome to the team @fbarriga! We've imported `caja-xattrs` to the MATE Desktop organisation :smile: 

  * https://github.com/mate-desktop/caja-xattrs

**Comment by raveit65** [comment]
Ok, i will close the PR now.

@fbarriga 
Your're welcome.
I will start with preparing caja-xattrs for a 1.19 release.

**Pull request closed without merging**
