### PR TITLE
xattr-tags: fix typo causing undefined reference

### LINKED ISSUE #29: Typo in xattr-tags extension
```diff
--- a/xattr-tags/caja-xattr-tags-extension.c
+++ b/xattr-tags/caja-xattr-tags-extension.c
@@ -101,7 +101,7 @@ static gchar *caja_xattr_tags_get_xdg_ta
     GFile *location;
     GFileInfo *info;

-    uri = caja_file_get_activation_uri (file);
+    uri = caja_file_info_get_activation_uri (file);
     location = g_file_new_for_uri (uri);
     info = g_file_query_info (location,
                               G_FILE_ATTRIBUTE_XATTR_XDG_TAGS,
```

### PR DESCRIPTION
**Pull request by yselkowitz**
Fixes #29.

### CODE REVIEW

**Comment by raveit65** [comment]
```
[rave@mother caja]$ grep -nr caja_file_get_activation_uri *
libcaja-private/caja-program-choosing.c:161:        uris = g_list_prepend (uris, caja_file_get_activation_uri (l->data));
libcaja-private/caja-file.h:440:char *                  caja_file_get_activation_uri                (CajaFile                   *file);
libcaja-private/caja-mime-actions.c:877:    activation_uri = caja_file_get_activation_uri (file);
libcaja-private/caja-mime-actions.c:1838:        uri = caja_file_get_activation_uri (file);
libcaja-private/caja-mime-actions.c:1860:        uri = caja_file_get_activation_uri (file);
libcaja-private/caja-mime-actions.c:1924:            uri = caja_file_get_activation_uri (file);
libcaja-private/caja-mime-actions.c:2200:        uri = caja_file_get_activation_uri (location->file);
libcaja-private/caja-file.c:3899:caja_file_get_activation_uri (CajaFile *file)
libcaja-private/caja-file.c:8366:	iface->get_activation_uri = caja_file_get_activation_uri;
src/file-manager/fm-tree-view.c:393:    uri = caja_file_get_activation_uri (file);
src/file-manager/fm-properties-window.c:307:		uri_to_display = caja_file_get_activation_uri (file);
src/file-manager/fm-properties-window.c:3048:	uri = caja_file_get_activation_uri (file);
src/file-manager/fm-properties-window.c:3160:	uri = caja_file_get_activation_uri (file);
src/file-manager/fm-directory-view.c:6238:		directory_uri = caja_file_get_activation_uri (data->target);
src/file-manager/fm-directory-view.c:6984:	uri = caja_file_get_activation_uri (file);
src/file-manager/fm-directory-view.c:7793:			activation_uri = caja_file_get_activation_uri (file);
src/file-manager/fm-directory-view.c:7887:		uri = caja_file_get_activation_uri (file);
[rave@mother caja]$ grep -nr caja_file_info_get_activation_uri *
docs/reference/libcaja-extension/libcaja-extension-sections.txt:109:caja_file_info_get_activation_uri
libcaja-extension/caja-file-info.h:77: *   See caja_file_info_get_activation_uri() for details.
libcaja-extension/caja-file-info.h:141:char         *caja_file_info_get_activation_uri   (CajaFileInfo *file);
libcaja-extension/caja-file-info.c:163:caja_file_info_get_activation_uri (CajaFileInfo *file)
```
hmm,....
@fbarriga
Can you please take a look at it.

**Comment by monsta** [comment]
That's correct, `caja_file_info_get_activation_uri` takes `CajaFileInfo` as argument, so it should be used here. In addition, "hack" used in `xattr-tags/caja-xattr-tags-extension.h` file can be removed. That is, unless @fbarriga really meant to use it there like that.

**Comment by raveit65** [comment]
@monsta 
So can we merge it like it is?

**Comment by monsta** [comment]
Yes, merged it and removed the hack.

**Pull request merged**
